# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 13:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import embed_video.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('article_date', models.DateTimeField(verbose_name='Дата публикации статьи')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание RU')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание RU')),
                ('article_video', embed_video.fields.EmbedVideoField(blank=True, help_text='URL video', null=True, verbose_name='Видео')),
                ('video_published', models.BooleanField(default='')),
                ('video_only', models.BooleanField(default='')),
                ('text_published', models.BooleanField(default='')),
                ('written_only', models.BooleanField(default='')),
            ],
            options={
                'verbose_name': 'Статья',
                'db_table': 'article',
                'ordering': ['-article_date'],
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('name', models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='Автор статьи')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Автор',
                'db_table': 'authors',
                'ordering': ('tree_id', 'level'),
                'verbose_name_plural': 'Авторы',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Имя категории')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Category', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Категорию',
                'db_table': 'category',
                'ordering': ('tree_id', 'level'),
                'verbose_name_plural': 'Категории',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание RU')),
                ('published', models.BooleanField(verbose_name='Опубликован')),
                ('published_main', models.BooleanField(default='', verbose_name='Опубликован на главной')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('category', mptt.fields.TreeForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides_article', to='article.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Имя тега')),
            ],
            options={
                'verbose_name': 'теги',
                'db_table': 'tags',
                'verbose_name_plural': 'тег',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_author', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='автор')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание')),
                ('work_title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('work_price', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='цена работы')),
                ('work_category', mptt.fields.TreeForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='article.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Примеры',
                'db_table': 'works',
                'verbose_name_plural': 'Примеры',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=mptt.fields.TreeForeignKey(blank=True, default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='article.Author', verbose_name='Автор статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=mptt.fields.TreeForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(related_name='tags', related_query_name='tags', to='article.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_works',
            field=models.ManyToManyField(blank=True, default='', related_name='works', related_query_name='works', to='article.Works', verbose_name='Примеры работ'),
        ),
    ]
